Repository Renascentinc/retina, pull requests merged in 2018-11, with the labels that each got.

#245 Amose.#234 clarify status button
  src/components/button-dropdown.vue
  src/routes/application.vue
  src/routes/tool-detail.vue
Labels: feature improvement

#265 Amose.#226 optimize for desktop
  package.json
  src/components/button-dropdown.vue
  src/components/extended-fab.vue
  src/main.js
  src/routes/application.vue
  src/routes/login.vue
  src/routes/new-tool.vue
  src/routes/new-user.vue
  src/routes/tool-detail.vue
  src/routes/tools.vue
  src/routes/user-detail.vue
  src/routes/users.vue
  src/styles/app.scss
  src/styles/drawer.scss
  src/styles/form-inputs.scss
  src/styles/navbar.scss
  src/styles/search-input.scss
  src/styles/search-result.scss
  yarn.lock
Labels: feature improvement

#268 Retina 192 config page
  src/components/add-result.vue
  src/components/config-item.vue
  src/components/header-card.vue
  src/routes/application.vue
  src/routes/configuration.vue
  src/routes/new-tool.vue
  src/routes/tools.vue
  src/routes/users.vue
  src/styles/drawer.scss
Labels: new feature

#280 Retina #236 add buttons refactor
  src/components/add-button.vue
  src/components/add-result.vue
  src/routes/tools.vue
  src/routes/users.vue
  src/styles/add-button.scss
Labels: feature improvement

#302 fixing config item bug
  src/routes/new-tool.vue
Labels: bug
